export interface Member {
  id: string;
  name: string;
  email: string;
  field: string;
  institution: string;
  institutionSlug?: string;
  photo?: string | null;
  detailUrl?: string;
}

export const members: Member[] = [
  // Universitas Airlangga
  {
    id: "member-1",
    name: "Andi Hamim Zaidan",
    email: "zaidan@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-2",
    name: "Angga Dito Fauzi",
    email: "a.dito.fauzi@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-3",
    name: "Imam Sapuan",
    email: "i_sapuan@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-4",
    name: "Aminatun",
    email: "aminatun@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-5",
    name: "Khusnul Ain",
    email: "k_ain@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-6",
    name: "Djony Izak Rudyardjo",
    email: "djony-i-r@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-7",
    name: "Dyah Hikmawati",
    email: "dyah-hikmawati@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-8",
    name: "Ersyzario Edo Yunata",
    email: "ersyzario.edo@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-9",
    name: "Febdian Rusydi",
    email: "rusydi@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-10",
    name: "Franky Chandra Satria Arisgraha",
    email: "frankysatria@gmail.com",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-11",
    name: "Herri Trilaksana",
    email: "herri-t@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-12",
    name: "Nuril Ukhrowiyah",
    email: "nurilukhrowiyah@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-13",
    name: "Nurul Fitriyah",
    email: "nurul.fitriyah@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-14",
    name: "Retna Apsari",
    email: "retna-a@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-15",
    name: "Pujiyanto",
    email: "pujiyanto@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-16",
    name: "Supadi",
    email: "supadi@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-17",
    name: "Suryani Dyah Astuti",
    email: "suryanidyah@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-18",
    name: "Winarno",
    email: "winarno@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-19",
    name: "Yhosep Gita Yhun Yhuwana",
    email: "yhuwana@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-20",
    name: "Jan Ady",
    email: "jan-a@fst.unair.ac.id",
    field: "Dosen",
    institution: "Universitas Airlangga",
    institutionSlug: "universitas-airlangga",
    photo: "/assets/members/profile.jpg",
  },

  // Universitas Negeri Surabaya
  {
    id: "member-21",
    name: "Abd. Kholiq",
    email: "kholiq@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-22",
    name: "Diah Hari Kusumawati",
    email: "diahkusumawati@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-23",
    name: "Titin Sunarti",
    email: "titinsunarti@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-24",
    name: "Suliyanah",
    email: "suliyanah@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-25",
    name: "Imam Sucahyo",
    email: "imamsucahyo@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-26",
    name: "Dzulkiflih",
    email: "dzulkiflih@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-27",
    name: "Endah Rahmawati",
    email: "endahrahmawati@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-28",
    name: "Mita Anggaryani",
    email: "mitaanggaryani@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-29",
    name: "Nugrahani Primary Putri",
    email: "nugrahaniprimary@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-30",
    name: "Munasir",
    email: "munasir_physics@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-31",
    name: "Tjipto Prastowo",
    email: "tjiptoprastowo@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-32",
    name: "Woro Setyarsih",
    email: "worosetyarsih@unesa.ac.id",
    field: "Dosen",
    institution: "Universitas Negeri Surabaya",
    institutionSlug: "universitas-negeri-surabaya",
    photo: "/assets/members/profile.jpg",
  },

  // Universitas Jember
  {
    id: "member-33",
    name: "Albertus Djoko Lesmono",
    email: "albert.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-34",
    name: "Sudarti",
    email: "sudarti.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-35",
    name: "Bambang Supriadi",
    email: "bambangsupriadi.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-36",
    name: "Dyah Arum Arimurti",
    email: "198911162024062001@mail.unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-37",
    name: "Singgih Bektiarso",
    email: "singgih.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-38",
    name: "Ernasari",
    email: "ernas0447@gmail.com",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-39",
    name: "Alex Harijanto",
    email: "alexharijanto.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-40",
    name: "Firdha Kusuma Ayu Anggraeni",
    email: "firdhakusuma@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-41",
    name: "Habibah Khusna Baihaqi",
    email: "habibahkhusnabaihaqi.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-42",
    name: "Ike Lusi Meilina",
    email: "ikelusimeilina@gmail.com",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-43",
    name: "Ike Lusi Meilina",
    email: "198905222023212045@mail.unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-44",
    name: "Kendid Mahmudi",
    email: "kendidmahmudi.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-45",
    name: "Lailatul Nuraini",
    email: "lailatul.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-46",
    name: "Maryani",
    email: "maryani.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-47",
    name: "Indrawati",
    email: "indrawatisutarto.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-48",
    name: "Nila Mutia Dewi",
    email: "nilamutia@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-49",
    name: "Sri Astutik",
    email: "astutirakhma@gmail.com",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-50",
    name: "Sutarto",
    email: "sutarto.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-51",
    name: "I Ketut Mahardika",
    email: "ketut.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-52",
    name: "Subiki",
    email: "subiki.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-53",
    name: "Trapsilo Prihandono",
    email: "trapsilo.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-54",
    name: "Yushardi",
    email: "yus_agk.fkip@unej.ac.id",
    field: "Dosen",
    institution: "Universitas Jember",
    institutionSlug: "universitas-jember",
    photo: "/assets/members/profile.jpg",
  },

  // UPN Veteran Jawa Timur
  {
    id: "member-55",
    name: "Akbar Sujiwa",
    email: "akbarsujiwa.ft@upnjatim.ac.id",
    field: "Dosen",
    institution: "UPN Veteran Jawa Timur",
    institutionSlug: "upn-veteran-jawa-timur",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-56",
    name: "Aprilia Dewi Ardiyanti",
    email: "aprilia_dewi.fisika@upnjatim.ac.id",
    field: "Dosen",
    institution: "UPN Veteran Jawa Timur",
    institutionSlug: "upn-veteran-jawa-timur",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-57",
    name: "Fajar Timur",
    email: "timur.ft@upnjatim.ac.id",
    field: "Dosen",
    institution: "UPN Veteran Jawa Timur",
    institutionSlug: "upn-veteran-jawa-timur",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-58",
    name: "Nailul Hasan",
    email: "nailul.hasan.fisika@upnjatim.ac.id",
    field: "Dosen",
    institution: "UPN Veteran Jawa Timur",
    institutionSlug: "upn-veteran-jawa-timur",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-59",
    name: "Nenni Mona Aruan",
    email: "nenni.mona.ft@upnjatim.ac.id",
    field: "Dosen",
    institution: "UPN Veteran Jawa Timur",
    institutionSlug: "upn-veteran-jawa-timur",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-60",
    name: "Nur Aini Fauziyah",
    email: "nur.aini.fisika@upnjatim.ac.id",
    field: "Dosen",
    institution: "UPN Veteran Jawa Timur",
    institutionSlug: "upn-veteran-jawa-timur",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-61",
    name: "Primasari Cahya Wardhani",
    email: "primasari.cahya.fisika@upnjatim.ac.id",
    field: "Dosen",
    institution: "UPN Veteran Jawa Timur",
    institutionSlug: "upn-veteran-jawa-timur",
    photo: "/assets/members/profile.jpg",
  },

  // Universitas Katolik Widya Mandala Surabaya
  {
    id: "member-62",
    name: "Anthony Wijaya",
    email: "anthony@ukwms.ac.id",
    field: "Dosen",
    institution: "Universitas Katolik Widya Mandala Surabaya",
    institutionSlug: "universitas-katolik-widya-mandala-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-63",
    name: "Elisabeth Pratidhina Founda Noviani",
    email: "elisa.founda@ukwms.ac.id",
    field: "Dosen",
    institution: "Universitas Katolik Widya Mandala Surabaya",
    institutionSlug: "universitas-katolik-widya-mandala-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-64",
    name: "G. Budijanto Untung",
    email: "budijanto@ukwms.ac.id",
    field: "Dosen",
    institution: "Universitas Katolik Widya Mandala Surabaya",
    institutionSlug: "universitas-katolik-widya-mandala-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-65",
    name: "Herwinarso",
    email: "herwinarso@ukwms.ac.id",
    field: "Dosen",
    institution: "Universitas Katolik Widya Mandala Surabaya",
    institutionSlug: "universitas-katolik-widya-mandala-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-66",
    name: "Jane Koswojo",
    email: "janekoswojo@gmail.com",
    field: "Dosen",
    institution: "Universitas Katolik Widya Mandala Surabaya",
    institutionSlug: "universitas-katolik-widya-mandala-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-67",
    name: "Bergitta Dwi Annawati",
    email: "bergittadwi@ukwms.ac.id",
    field: "Dosen",
    institution: "Universitas Katolik Widya Mandala Surabaya",
    institutionSlug: "universitas-katolik-widya-mandala-surabaya",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-68",
    name: "Tri Lestari",
    email: "trilestari@ukwms.ac.id",
    field: "Dosen",
    institution: "Universitas Katolik Widya Mandala Surabaya",
    institutionSlug: "universitas-katolik-widya-mandala-surabaya",
    photo: "/assets/members/profile.jpg",
  },

  // Universitas Nusa Cendana
  {
    id: "member-69",
    name: "Ali Warsito",
    email: "alifis.aw@gmail.com",
    field: "Dosen",
    institution: "Universitas Nusa Cendana",
    institutionSlug: "universitas-nusa-cendana",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-70",
    name: "Zakarias Seba Ngara",
    email: "zakariasngara@staf.undana.ac.id",
    field: "Dosen",
    institution: "Universitas Nusa Cendana",
    institutionSlug: "universitas-nusa-cendana",
    photo: "/assets/members/profile.jpg",
  },
  {
    id: "member-71",
    name: "Hadi Imam Sutaji",
    email: "hadi.i.sutaji@staf.undana.ac.id",
    field: "Dosen",
    institution: "Universitas Nusa Cendana",
    institutionSlug: "universitas-nusa-cendana",
    photo: "/assets/members/profile.jpg",
  },

  // ITS NU Pasuruan
  {
    id: "member-72",
    name: "Nurul Hidayah Almubarokah",
    email: "nurulhidayaham@itsnupasuruan.ac.id",
    field: "Dosen",
    institution: "ITS NU Pasuruan",
    institutionSlug: "its-nu-pasuruan",
    photo: "/assets/members/profile.jpg",
  },

  // Universitas Muhammadiyah Ponorogo
  {
    id: "member-73",
    name: "Munaji",
    email: "munaji@umpo.ac.id",
    field: "Dosen",
    institution: "Universitas Muhammadiyah Ponorogo",
    institutionSlug: "universitas-muhammadiyah-ponorogo",
    photo: "/assets/members/profile.jpg",
  },
];